language: python
python: "2.7"

env:
  global:
  - PACKAGE_VERSION="v1.0.${TRAVIS_BUILD_NUMBER}"

script:
  - docker build -t arieszhang/cat-filter:latest .
  - python -m test.TransformerTest
  - docker image ls

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
    script:
      - docker push arieszhang/cat-filter:latest
