language: python
python: "2.7"

env:
  global:
  - PACKAGE_VERSION="v1.0.${TRAVIS_BUILD_NUMBER}"
  - TAG="arieszhang/cat-filter:${PACKAGE_VERSION}"

script:
  - docker build -t ${TAG}
  - python -m tests

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
    script:
      - docker push ${TAG}