language: python
python: "2.7"

env:
  global:
  - PACKAGE_VERSION="v1.0.${TRAVIS_BUILD_NUMBER}"
  - DOCKER_REPO=arieszhang/cat-filter
  - TAG=${DOCKER_REPO}:${PACKAGE_VERSION}
  - TAG_LATEST=${DOCKER_REPO}:latest

script:
  - python -m test.TransformerTest
  - docker build -t ${TAG} .
  - docker tag $(docker images ls -q $TAG) ${TAG_LATEST}
  - docker image ls

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - 

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
    script:
      - docker push ${TAG} && docker push ${TAG_LATEST}